profile_type: Sersic #Gaussian_PSF #Sersic # EBulgeDisk, Gaussian
nn: 40
tru_g1: 0.2 #ellipticity
tru_g2: 0.2 #ellipticity
Convolve: True #set to false when using stars, i.e, PSF profiles
placer_method: random_ring #random_box #random_ring

#Profiles dict of properties
Sersic:
    sersiccut:
    tru_rad: 4.0 #half_light_radius
    tru_sersicn: 2 #sersic index
    tru_sb: 2.0 #fiducial surface brightness

Gaussian:
    tru_flux: 70
    tru_sigma: 2

EBulgeDisk:
    tru_bulge_rad: 4.0 #half_light_radius
    tru_bulge_sersicn: 2 #sersic index
    tru_bulge_flux: 50 #half_light_radius
    tru_disk_hlr: 4.0
    tru_disk_tilt: 45 #tilt in degrees
    tru_disk_flux: 50
    tru_disk_scale_h_over_r: 1.0
    tru_theta: 45 #rotate disk angle degree

Gaussian_PSF: #for stars not randomes in case not defined
    flux: 1.0 #1.0
    sigma: 2.0 #2.0

Stamp_PSF: # import PSF stamp defined in catalog

#Placer_Methods
random_box: # units in stamp fractional pixels (0,1.0) where 1.0 is the stampsize pixel
    xmin:
    xmax:
    ymin: 0.2
    ymax: 0.8
    x: 0.2
    y:

random_ring:
   rmin: 16 #pixels
   rmax: 20 #pixels
   theta_min:  #angle in np.pi units
   theta_max:  #angle in np.pi units
   r:
   theta: #angle in np.pi units